name: Helm Deploy
on:
  push:
    branches: 
      - main
    paths:
      - helm/**

env:  
  AWS_REGION : "<aws-region>"
  ASSUME_ROLE_ARN: "arn:aws:iam::<aws-account-id>:role/rak-role-with-oidc-for-eks"
  CLUSTER_NAME: "rak-cluster"
  HELM_CHART: "javaapp"

permissions:
      id-token: write
      contents: read
jobs:
  deploy-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.ASSUME_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy
        run: |
          cd helm/webapp
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
          helm upgrade ${{ env.HELM_CHART }} --install . --set=image.tag="latest"